### ISSUE TITLE
Safari: Reference Error thrown to malarkey function call

### ISSUE THREAD

**Issue by co16353sidak** [dracula/dracula.github.io#74] opened 2019-05-21 19:36 UTC
As displayed in the screenshot the `malarkey` function call seems to have been error out as it seems it is not defined in the scope of the global function, the browser console seems to be giving out an error for the same.
I would love to work on this and send a PR with fixes. 🥇 

Screenshot:
<img width="1280" alt="Screenshot 2019-05-22 at 1 04 24 AM" src="https://user-images.githubusercontent.com/35738138/58125191-a380a380-7c2d-11e9-998c-5ad0d42b74f4.png">

**Comment by hacknug** [comment] 2019-06-03 18:57
Can't reproduce the issue as it seems to download just fine. Would be open to a PR that adds a conditional to make sure `malarkey` is defined before trying to use it.

Please let me know if you need anything else 👍

**Comment by zenorocha** [comment] 2020-01-11 14:18
This should be fixed now, let me know if that's not the case.

Thanks for reporting @co16353sidak!

**Closed by zenorocha** 2020-01-11 14:18 UTC
